title: Hello Semgrep # a name for your Learning Lab course
tagline: Learn to set up continuous code scanning with Semgrep # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: lab-hello-semgrep    # the name of the repository when it is created for the learner
  repo: lab-hello-semgrep   # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

# Before - forks vulnerable repo
# * Set the Semgrep repo secret
# * Set up semgrep.yml
# * Issue PR with X == X and watch it fail
# * Change the code to 3 = 5 or something else and have it succeed
# * Walk briefly though Semgrep App - what it does, where things are
# * Intro to ellipses operator - block eval(...)
# * Intro to metavar
# * Warn on new route - audit only
# * Create owasp_devslop community Slack channel - point webhook there
# * Audit @csrf_exempt or other authn/authz
# * XSS
# * < write some custom rule and add it to policy >

steps:
# Step 1: EDIT HERE - INTERNAL COMMENT DESCRIBING STEP 
- title: Step 1 Title # the title of the step, shown to the learner in the course progress page
  description: Description # a description of the step, shown to the learner in the course progress page
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
- title: Step 2 Title # the title of the step, shown to the learner in the course progress page
  description: Description 2 # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: EDIT HERE - INTERNAL COMMENT FOR STEP 3
- title: Step 3 Title # the title of the step, shown to the learner in the course progress page
  description: Description 3 # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: EDIT HERE - INTERNAL COMMENT FOR STEP 4
- title: Step 4 Title # the title of the step, shown to the learner in the course progress page
  description: Description 4 # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: EDIT HERE - INTERNAL COMMENT FOR STEP 5
- title: Step 5 Title # the title of the step, shown to the learner in the course progress page
  description: Description 5 # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

